In [1]:
import cipo
from cipo import user

In [2]:
code_obs = 'Y28'          # código do observatório (ex: OASI)
type_object = 'NEOCP'       # ou 'PCCP'

In [3]:
df_complete = user.mpc_objects(type_object)

Downloaded 94 objects from page NEOCP.

In [5]:
df_complete

,Temp Desig,Score,Discovery,R.A.,Decl.,V,Updated,Note,NObs,Arc,H,Not_Seen_dys
0,Sar2870,98.0,2026 02 25.0,10 09.3,+22 10,19.0,Updated Feb. 25.11 UT,NaN,28.0,0.14,27.0,0.046
1,Sar2869,98.0,2026 02 24.9,10 00.8,+19 37,20.5,Updated Feb. 25.09 UT,NaN,12.0,0.13,24.4,0.068
2,A11yzTN,10.0,2026 02 11.8,12 46.3,+05 58,19.5,Updated Feb. 25.09 UT,NaN,39.0,40.54,9.4,0.120
3,T61JM02,96.0,2026 02 24.6,09 42.7,+07 44,19.6,Added Feb. 24.74 UT,NaN,3.0,0.05,19.5,0.477
4,T61JM01,100.0,2026 02 24.6,09 40.7,+07 33,18.5,Added Feb. 24.74 UT,NaN,3.0,0.05,16.7,0.477
5,ZTF10Bn,98.0,2026 02 24.3,10 08.1,-03 31,19.0,Updated Feb. 25.14 UT,NaN,4.0,0.11,26.4,0.755
6,ZTF10Bi,100.0,2026 02 24.2,09 47.5,+34 31,18.1,Updated Feb. 24.69 UT,S,4.0,0.03,25.2,0.966
7,P12m2Rl,100.0,2026 02 24.6,13 58.0,-09 53,20.5,Updated Feb. 24.76 UT,NaN,5.0,0.08,22.4,0.509
8,ZTF10Bg,100.0,2026 02 23.4,20 27.2,-37 00,24.0,Added Feb. 24.61 UT,NaN,4.0,0.04,25.8,1.667
9,ZTF10Bf,100.0,2026 02 23.4,13 47.2,+17 16,20.8,Added Feb. 24.60 UT,NaN,4.0,0.02,30.8,1.726
10,C1CDFZ5,77.0,2026 02 24.5,14 05.7,+14 29,21.5,Added Feb. 24.55 UT,NaN,4.0,0.02,18.9,0.608
11,C1CDCT5,100.0,2026 02 24.5,12 31.9,+26 38,22.5,Updated Feb. 24.55 UT,NaN,7.0,0.05,27.1,0.603
12,C1CD955,100.0,2026 02 24.4,11 55.2,+30 51,21.7,Updated Feb. 24.53 UT,NaN,8.0,0.08,25.9,0.625
13,C45WJW1,88.0,2026 02 24.5,15 35.9,+38 35,19.6,Updated Feb. 25.14 UT,NaN,21.0,0.67,20.5,0.018
14,CE90Y32,100.0,2026 02 24.5,14 57.3,+05 38,20.9,Updated Feb. 24.54 UT,NaN,12.0,0.08,25.5,0.612
15,C1CD7L5,98.0,2026 02 24.5,11 48.9,+27 36,22.1,Updated Feb. 24.55 UT,NaN,8.0,0.09,28.4,0.605
16,P12lZEB,86.0,2026 02 24.4,11 46.2,+11 16,19.8,Updated Feb. 25.11 UT,NaN,20.0,0.72,24.9,0.049
17,C1CD665,98.0,2026 02 24.4,11 19.3,+33 29,22.3,Updated Feb. 24.54 UT,NaN,10.0,0.10,28.0,0.622
18,C1CD0E5,95.0,2026 02 24.4,10 57.5,+29 39,22.7,Updated Feb. 24.48 UT,NaN,6.0,0.04,25.0,0.684
19,C1CC4M5,83.0,2026 02 24.3,09 58.1,-02 28,23.0,Added Feb. 24.44 UT,NaN,3.0,0.01,25.8,0.821
20,C1CCA05,98.0,2026 02 24.3,09 48.6,+21 15,20.7,Updated Feb. 25.14 UT,NaN,12.0,0.78,26.9,0.031
21,C45WJF1,86.0,2026 02 24.4,13 20.5,+40 24,19.6,Updated Feb. 25.13 UT,NaN,27.0,0.74,25.3,0.027
22,CE8XFV2,100.0,2026 02 24.4,12 23.3,+03 12,21.0,Updated Feb. 24.50 UT,NaN,11.0,0.13,23.4,0.664
23,CE8TQD2,100.0,2026 02 24.3,11 14.9,-01 21,20.7,Updated Feb. 24.41 UT,NaN,12.0,0.08,27.1,0.748
24,orA2763,100.0,2026 02 24.1,12 34.9,+02 38,20.0,Added Feb. 24.33 UT,NaN,3.0,0.02,20.5,1.017
25,C45WET1,89.0,2026 02 24.2,09 13.6,+18 50,19.2,Updated Feb. 25.08 UT,NaN,52.0,0.83,25.5,0.081
26,C1CATD5,98.0,2026 02 24.3,09 04.7,-03 33,21.8,Updated Feb. 25.06 UT,NaN,11.0,0.78,26.4,0.100
27,CE8N232,100.0,2026 02 24.3,09 59.9,+04 15,20.7,Updated Feb. 25.08 UT,NaN,11.0,0.81,22.8,0.086
28,CE8LNQ2,86.0,2026 02 24.2,09 40.6,+02 40,20.8,Updated Feb. 25.10 UT,NaN,18.0,0.85,26.9,0.063
29,C1CA1L5,100.0,2026 02 24.2,08 15.1,+27 19,22.0,Updated Feb. 24.30 UT,NaN,10.0,0.11,23.8,0.848
30,C1CA1K5,98.0,2026 02 24.2,08 59.7,+20 57,21.1,Updated Feb. 25.04 UT,NaN,11.0,0.60,27.4,0.357
31,C1C9Y25,98.0,2026 02 24.2,08 13.4,+23 15,22.1,Updated Feb. 25.11 UT,NaN,11.0,0.90,24.4,0.053
32,v23feb6,100.0,2026 02 23.0,02 04.8,-04 02,21.4,Updated Feb. 25.11 UT,NaN,12.0,2.00,18.9,0.132
33,CE8K6Y2,98.0,2026 02 23.5,13 02.2,-02 16,19.9,Updated Feb. 24.11 UT,NaN,15.0,0.58,26.4,1.070
34,C1C88V5,98.0,2026 02 23.5,12 16.1,+32 01,21.7,Updated Feb. 24.39 UT,NaN,14.0,0.83,26.0,0.852
35,C1C7V05,91.0,2026 02 23.5,12 47.4,+12 38,21.4,Updated Feb. 24.40 UT,NaN,22.0,0.87,24.8,0.824
36,C1C7T05,100.0,2026 02 23.4,12 14.6,+06 24,22.0,Updated Feb. 24.45 UT,NaN,15.0,0.99,24.3,0.708
37,ST26B48,86.0,2026 02 23.4,09 56.6,-00 13,20.1,Updated Feb. 24.25 UT,NaN,22.0,0.79,26.6,0.916
38,CE8GYY2,100.0,2026 02 23.4,12 24.5,+08 19,21.9,Added Feb. 23.47 UT,NaN,4.0,0.02,22.9,1.687
39,ST26B47,100.0,2026 02 23.4,22 25.4,+08 47,32.4,Updated Feb. 23.70 UT,NaN,9.0,0.06,31.8,1.646
40,C1C7FZ5,91.0,2026 02 23.4,10 45.9,+30 06,22.5,Updated Feb. 23.53 UT,NaN,8.0,0.09,27.0,1.629
41,C1C7EZ5,100.0,2026 02 23.4,10 38.0,+33 09,22.0,Updated Feb. 24.21 UT,NaN,13.0,0.78,21.8,0.943
42,CE8GHW2,91.0,2026 02 23.4,12 17.6,+08 25,22.0,Updated Feb. 24.46 UT,NaN,19.0,1.02,22.9,0.701
43,C1C7DN5,95.0,2026 02 23.4,10 51.5,+29 16,22.5,Updated Feb. 24.29 UT,NaN,10.0,0.82,23.2,0.905
44,C45W821,72.0,2026 02 23.4,11 42.7,-00 27,19.7,Updated Feb. 24.96 UT,NaN,53.0,1.55,27.7,0.199
45,C1C60U5,98.0,2026 02 23.4,09 45.3,+07 28,22.6,Updated Feb. 24.22 UT,NaN,20.0,0.83,20.2,0.934
46,CE8AMJ2,46.0,2026 02 23.4,11 30.8,+14 40,21.9,Updated Feb. 24.47 UT,NaN,23.0,1.05,16.7,0.733
47,CE89FX2,86.0,2026 02 23.4,13 13.0,-43 07,19.9,Updated Feb. 24.61 UT,NaN,33.0,0.95,27.2,0.833
48,CE88H12,93.0,2026 02 23.4,11 35.7,+01 35,21.3,Updated Feb. 24.56 UT,NaN,16.0,1.11,25.0,0.675
49,CE83CU2,100.0,2026 02 23.3,10 53.7,+02 52,21.1,Updated Feb. 24.16 UT,NaN,11.0,0.82,25.4,1.007
50,CE84E12,86.0,2026 02 23.3,11 08.3,+25 33,21.1,Updated Feb. 24.32 UT,NaN,22.0,0.98,28.1,0.849
51,CE82VN2,86.0,2026 02 23.3,10 56.6,+08 36,21.7,Updated Feb. 24.26 UT,NaN,24.0,0.92,27.1,0.904
52,C45W5U1,74.0,2026 02 23.3,14 00.5,+38 30,19.3,Updated Feb. 25.02 UT,NaN,40.0,1.57,27.8,0.257
53,C1C4K95,89.0,2026 02 23.3,08 29.4,+09 08,22.6,Updated Feb. 24.13 UT,NaN,11.0,0.83,22.1,1.030
54,C45W551,84.0,2026 02 23.3,09 24.7,-23 44,20.6,Updated Feb. 24.49 UT,NaN,32.0,0.95,27.0,0.951
55,C45W4V1,86.0,2026 02 23.3,10 10.6,-10 27,20.8,Updated Feb. 24.08 UT,NaN,19.0,0.76,26.6,1.103
56,CE7Y8A2,81.0,2026 02 23.3,10 34.3,+05 19,20.6,Updated Feb. 24.30 UT,NaN,27.0,1.02,25.1,0.856
57,CE7Y2P2,86.0,2026 02 23.3,10 18.4,-00 22,21.0,Updated Feb. 24.28 UT,NaN,22.0,1.00,28.5,0.875
58,C45W3X1,100.0,2026 02 23.3,20 59.1,-18 03,30.1,Updated Feb. 23.31 UT,S,3.0,0.01,29.2,1.870
59,C1C3XP5,86.0,2026 02 23.2,08 22.8,+09 59,21.9,Updated Feb. 25.14 UT,NaN,20.0,1.89,25.9,0.027
60,CE7U292,84.0,2026 02 23.2,09 44.4,+11 01,20.7,Updated Feb. 24.39 UT,NaN,26.0,0.97,26.2,0.953
61,CE7T552,42.0,2026 02 23.2,09 35.8,+12 51,21.3,Updated Feb. 24.82 UT,NaN,24.0,16.05,19.9,0.667
62,CE7PRF2,86.0,2026 02 23.2,09 42.1,+07 34,21.6,Updated Feb. 24.28 UT,NaN,25.0,0.99,26.7,0.944
63,C45W2H1,72.0,2026 02 23.2,09 19.0,+20 47,20.1,Updated Feb. 25.14 UT,NaN,70.0,1.64,26.2,0.304
64,CE7LUH2,78.0,2026 02 23.2,08 38.7,+10 38,20.7,Updated Feb. 25.08 UT,NaN,24.0,1.90,24.7,0.088
65,CE7F722,86.0,2026 02 22.3,10 38.6,+18 55,21.6,Updated Feb. 23.26 UT,NaN,24.0,0.97,27.2,1.907
66,A11yCiF,100.0,2026 02 21.4,21 12.9,-06 34,32.5,Updated Feb. 24.24 UT,NaN,4.0,0.04,28.8,3.722
67,PDO0100,100.0,2026 02 21.0,10 39.9,+12 12,21.1,Updated Feb. 24.23 UT,NaN,3.0,0.04,22.7,4.097
68,ODI2462,10.0,2026 02 19.8,14 04.3,+05 31,21.5,Updated Feb. 24.72 UT,NaN,29.0,5.80,21.1,0.522
69,orA2414,100.0,2026 02 21.0,09 52.8,-01 34,21.5,Updated Feb. 24.23 UT,NaN,3.0,0.02,23.4,4.109
70,DNA0007,100.0,2026 02 20.7,22 03.3,+73 37,27.9,Updated Feb. 24.23 UT,NaN,3.0,0.00,31.0,4.401
71,X89330,76.0,2026 02 19.8,12 35.1,-05 16,18.4,Updated Feb. 24.23 UT,NaN,3.0,0.03,15.1,5.352
72,X89255,100.0,2026 02 19.7,11 21.3,-00 12,17.9,Updated Feb. 24.23 UT,NaN,3.0,0.03,15.8,5.390
73,C1AZHH5,100.0,2026 02 20.2,09 01.7,+51 09,24.0,Updated Feb. 24.23 UT,NaN,4.0,0.02,24.1,4.916
74,A11yweL,100.0,2026 02 19.5,11 54.1,+57 46,22.0,Updated Feb. 24.24 UT,NaN,4.0,0.04,27.4,5.623
75,P22lUn6,19.0,2026 02 19.4,10 42.8,+19 10,21.9,Updated Feb. 24.40 UT,NaN,18.0,4.97,15.1,0.788
76,P22lUn8,15.0,2026 02 19.4,10 32.9,+17 47,21.4,Updated Feb. 23.30 UT,NaN,18.0,25.79,19.6,1.880
77,A11yqBr,100.0,2026 02 18.2,15 53.8,+29 01,19.4,Updated Feb. 24.23 UT,NaN,4.0,0.04,16.4,6.928
78,P22lMSN,41.0,2026 02 17.5,15 05.6,+09 25,21.9,Updated Feb. 23.49 UT,NaN,12.0,9.87,18.5,1.686
79,A11ynxx,100.0,2026 02 17.2,18 21.0,+36 32,19.9,Updated Feb. 24.23 UT,NaN,4.0,0.02,19.0,7.893
80,X89042,87.0,2026 02 14.8,11 15.5,+31 49,20.8,Updated Feb. 24.24 UT,NaN,3.0,0.03,14.9,10.315
81,P12lFxz,100.0,2026 02 14.4,10 28.4,-14 03,21.8,Updated Feb. 24.24 UT,NaN,3.0,0.02,23.5,10.708
82,P12lDlO,30.0,2026 02 14.4,08 59.7,-07 05,22.1,Updated Feb. 24.29 UT,NaN,18.0,36.78,19.3,0.887
83,P12lDlR,23.0,2026 02 14.4,08 46.7,-00 45,22.4,Updated Feb. 24.24 UT,NaN,16.0,6.74,20.1,3.989
84,ZTF10BV,100.0,2026 02 14.2,15 17.8,-61 55,22.8,Updated Feb. 24.23 UT,NaN,5.0,0.09,25.5,10.917
85,P22lyTB,47.0,2026 02 13.6,11 48.4,+15 04,21.6,Updated Feb. 24.47 UT,NaN,19.0,10.81,20.3,0.746
86,P12ly16,20.0,2026 02 13.5,11 04.9,-05 53,20.9,Updated Feb. 24.24 UT,NaN,4.0,0.04,23.5,11.632
87,ST26B25,96.0,2026 02 09.2,22 28.5,+09 40,34.6,Updated Feb. 24.23 UT,NaN,13.0,1.24,30.0,15.647
88,ST26B20,98.0,2026 02 08.3,03 26.6,-69 36,26.6,Updated Feb. 24.24 UT,NaN,9.0,1.06,28.4,15.811
89,ZTF10BB,100.0,2026 02 03.3,20 26.9,+26 07,27.4,Updated Feb. 25.14 UT,NaN,8.0,1.03,25.7,21.875
90,P22l8RJ,54.0,2026 01 28.6,13 08.3,-27 10,21.6,Updated Feb. 23.49 UT,NaN,12.0,25.84,19.5,1.720
91,P12lwY3,NaN,NaN,NaN,NaN,NaN,Moved to the PCCP,NaN,NaN,NaN,NaN,NaN
92,C19RNP5,NaN,NaN,NaN,NaN,NaN,Moved to the PCCP,NaN,NaN,NaN,NaN,NaN
93,P22bZYt,NaN,NaN,NaN,NaN,NaN,Moved to the PCCP,NaN,NaN,NaN,NaN,NaN

In [7]:
local = user.get_observatory_location(code_obs)
if local is None:
    raise ValueError("Observatório não encontrado")

In [8]:
altitude_min = 20          # graus
time_min = 45             # minutos

df_filtared = user.filter_visible_objects(df_complete, local,
                                          altitude_min=altitude_min,
                                          time_min_minutes=time_min)

if df_filtared.empty:
    print("None.")
else:
    df_filtared
    cols_show = ['Temp Desig', 'R.A.', 'Decl.', 'V', 'Visible_Minutes', 'Max_Alt']
    display(df_filtared[cols_show])

Warning: 3 objects ignored due to invalid coordinate format.

   Temp Desig     R.A.   Decl.     V  Visible_Minutes  Max_Alt
0     Sar2870  10 09.3  +22 10  19.0              540     59.2
1     Sar2869  10 00.8  +19 37  20.5              540     61.7
2     A11yzTN  12 46.3  +05 58  19.5              570     75.4
3     T61JM02  09 42.7  +07 44  19.6              555     73.6
4     T61JM01  09 40.7  +07 33  18.5              570     73.8
5     ZTF10Bn  10 08.1  -03 31  19.0              570     84.9
6     ZTF10Bi  09 47.5  +34 31  18.1              480     46.9
7     P12m2Rl  13 58.0  -09 53  20.5              585     87.8
8     ZTF10Bg  20 27.2  -37 00  24.0              570     61.8
9     ZTF10Bf  13 47.2  +17 16  20.8              540     64.1
10    C1CDFZ5  14 05.7  +14 29  21.5              540     66.9
11    C1CDCT5  12 31.9  +26 38  22.5              525     54.8
12    C1CD955  11 55.2  +30 51  21.7              495     50.5
13    C45WJW1  15 35.9  +38 35  19.6              435     42.8
14    CE90Y32  14 57.3  +05 38  20.9              570     75.6
15    C1CD7L5  11 48.9  +27 36  22.1              510     53.8
16    P12lZEB  11 46.2  +11 16  19.8              555     70.1
17    C1CD665  11 19.3  +33 29  22.3              480     47.9
18    C1CD0E5  10 57.5  +29 39  22.7              495     51.8
19    C1CC4M5  09 58.1  -02 28  23.0              585     83.8
20    C1CCA05  09 48.6  +21 15  20.7              540     60.1
21    C45WJF1  13 20.5  +40 24  19.6              450     41.0
22    CE8XFV2  12 23.3  +03 12  21.0              570     78.2
23    CE8TQD2  11 14.9  -01 21  20.7              585     82.7
24    orA2763  12 34.9  +02 38  20.0              570     78.8
25    C45WET1  09 13.6  +18 50  19.2              540     62.5
26    C1CATD5  09 04.7  -03 33  21.8              570     84.8
27    CE8N232  09 59.9  +04 15  20.7              570     77.0
28    CE8LNQ2  09 40.6  +02 40  20.8              570     78.7
29    C1CA1L5  08 15.1  +27 19  22.0              525     54.0
30    C1CA1K5  08 59.7  +20 57  21.1              525     60.4
31    C1C9Y25  08 13.4  +23 15  22.1              525     58.1
32    v23feb6  02 04.8  -04 02  21.4              555     85.1
33    CE8K6Y2  13 02.2  -02 16  19.9              585     83.6
34    C1C88V5  12 16.1  +32 01  21.7              495     49.4
35    C1C7V05  12 47.4  +12 38  21.4              555     68.8
36    C1C7T05  12 14.6  +06 24  22.0              555     75.0
37    ST26B48  09 56.6  -00 13  20.1              585     81.6
38    CE8GYY2  12 24.5  +08 19  21.9              570     73.1
39    ST26B47  22 25.4  +08 47  32.4              540     72.3
40    C1C7FZ5  10 45.9  +30 06  22.5              495     51.3
41    C1C7EZ5  10 38.0  +33 09  22.0              480     48.3
42    CE8GHW2  12 17.6  +08 25  22.0              555     73.0
43    C1C7DN5  10 51.5  +29 16  22.5              510     52.1
44    C45W821  11 42.7  -00 27  19.7              585     81.7
45    C1C60U5  09 45.3  +07 28  22.6              555     73.8
46    CE8AMJ2  11 30.8  +14 40  21.9              555     66.7
47    CE89FX2  13 13.0  -43 07  19.9              585     55.4
48    CE88H12  11 35.7  +01 35  21.3              570     79.8
49    CE83CU2  10 53.7  +02 52  21.1              570     78.5
50    CE84E12  11 08.3  +25 33  21.1              510     55.9
51    CE82VN2  10 56.6  +08 36  21.7              555     72.8
52    C45W5U1  14 00.5  +38 30  19.3              465     42.9
53    C1C4K95  08 29.4  +09 08  22.6              555     72.2
54    C45W551  09 24.7  -23 44  20.6              600     74.9
55    C45W4V1  10 10.6  -10 27  20.8              585     88.1
56    CE7Y8A2  10 34.3  +05 19  20.6              570     76.0
57    CE7Y2P2  10 18.4  -00 22  21.0              570     81.7
58    C45W3X1  20 59.1  -18 03  30.1              570     80.6
59    C1C3XP5  08 22.8  +09 59  21.9              570     71.4
60    CE7U292  09 44.4  +11 01  20.7              555     70.3
61    CE7T552  09 35.8  +12 51  21.3              555     68.5
62    CE7PRF2  09 42.1  +07 34  21.6              555     73.8
63    C45W2H1  09 19.0  +20 47  20.1              540     60.6
64    CE7LUH2  08 38.7  +10 38  20.7              555     70.7
65    CE7F722  10 38.6  +18 55  21.6              540     62.5
66    A11yCiF  21 12.9  -06 34  32.5              570     87.2
67    PDO0100  10 39.9  +12 12  21.1              555     69.2
68    ODI2462  14 04.3  +05 31  21.5              570     75.9
69    orA2414  09 52.8  -01 34  21.5              570     83.0
71     X89330  12 35.1  -05 16  18.4              585     86.7
72     X89255  11 21.3  -00 12  17.9              570     81.6
73    C1AZHH5  09 01.7  +51 09  24.0              360     30.2
74    A11yweL  11 54.1  +57 46  22.0              240     23.6
75    P22lUn6  10 42.8  +19 10  21.9              540     62.2
76    P22lUn8  10 32.9  +17 47  21.4              540     63.6
77    A11yqBr  15 53.8  +29 01  19.4              495     52.3
78    P22lMSN  15 05.6  +09 25  21.9              570     72.0
79    A11ynxx  18 21.0  +36 32  19.9              465     44.7
80     X89042  11 15.5  +31 49  20.8              495     49.6
81    P12lFxz  10 28.4  -14 03  21.8              585     84.4
82    P12lDlO  08 59.7  -07 05  22.1              585     87.8
83    P12lDlR  08 46.7  -00 45  22.4              585     81.9
84    ZTF10BV  15 17.8  -61 55  22.8              525     36.7
85    P22lyTB  11 48.4  +15 04  21.6              555     66.3
86    P12ly16  11 04.9  -05 53  20.9              585     87.1
87    ST26B25  22 28.5  +09 40  34.6              540     71.4
88    ST26B20  03 26.6  -69 36  26.6              435     29.2
89    ZTF10BB  20 26.9  +26 07  27.4              495     55.0
90    P22l8RJ  13 08.3  -27 10  21.6              600     71.4

In [10]:
if not df_filtared.empty:
    object_selected = df_filtared.iloc[0]['Temp Desig']


    page_ephemeris = user.fetch_mpc_data(which=type_object, obscode=code_obs)

    if page_ephemeris:
        dict_ephemeris = user.parse_mpc_data(page_ephemeris)
        if object_selected in dict_ephemeris:
            df_ephemeris = dict_ephemeris[object_selected]
            #print(f"\nEfemérides de {object_selected}:")
            display(df_ephemeris)
        else:
            print(object_selected)
    else:
        print("Falha ao obter página de efemérides.")
else:
    print("Nenhum objeto filtrado para buscar efemérides.")

Starting ephemeris collection from page NEOCP...
Ephemeris collected successfully.

,Date,UT,R.A. (J2000),Decl,Elong,V,Motion min,Motion PA,Object Azi,Object Alt,Sun Alt,Moon Phase,Moon Dist,Moon Alt
0,2026 02 25,02,10 11 16.3,+23 20 07,165.1,19.1,46.17,204.2,191,57,-69,0.57,072,9
1,2026 02 25,03,10 09 53.7,+22 37 31,165.6,19.0,47.12,203.9,165,57,-72,0.57,072,-3
2,2026 02 25,04,10 08 31.0,+21 53 59,166.2,19.0,47.98,203.5,143,51,-64,0.58,071,-16
3,2026 02 25,05,10 07 08.9,+21 09 33,166.6,19.0,48.74,203.0,128,41,-52,0.58,070,-29
4,2026 02 25,06,10 05 48.1,+20 24 15,167.1,18.9,49.41,202.3,119,29,-39,0.58,070,-41
5,2026 02 25,22,09 46 09.9,+06 57 13,167.8,18.7,58.86,201.1,257,29,-17,0.66,062,53
6,2026 02 25,23,09 44 43.1,+06 02 01,167.2,18.7,59.64,201.5,253,44,-31,0.66,061,50
7,2026 02 26,00,09 43 14.0,+05 06 16,166.6,18.7,60.34,201.8,245,58,-45,0.67,061,42
8,2026 02 26,01,09 41 43.3,+04 10 00,165.9,18.7,60.92,202.0,226,72,-58,0.67,061,33
9,2026 02 26,02,09 40 11.5,+03 13 17,165.2,18.8,61.39,202.0,169,78,-69,0.68,060,21

In [ ]:
df_visible = user.process_mpc_data(code_obs, page_type=type_object, interactive_mode=True)

Total objects downloaded: 94
Filtering objects with Alt > 10° for ~30 min at Y28...
Warning: 3 objects ignored due to invalid coordinate format.

============================================================
VISIBLE OBJECTS AT Y28
============================================================
Temp Desig    R.A.  Decl.    V  Visible_Minutes  Max_Alt
   P12m2Rl 13 58.1 -09 53 20.5              660     88.3
   P12lDlO 08 59.7 -07 05 22.1              660     88.3
   C45W4V1 10 10.6 -10 27 20.8              660     88.1
   A11yCiF 21 12.9 -06 34 32.5              645     87.6
   P12ly16 11 04.9 -05 53 20.9              660     86.7
    X89330 12 35.1 -05 16 18.4              660     86.6
   v23feb6 02 04.8 -04 02 21.4              630     84.9
   ZTF10Bn 10 08.3 -03 31 19.0              660     84.8
   C1CATD5 09 04.7 -03 33 21.8              660     84.6
   P12lFxz 10 28.4 -14 03 21.8              675     84.5
   C1CC4M5 09 58.1 -02 28 23.0              660     83.9
   CE8K6Y2 13 02.2 -02 18 19.9              660     83.5
   orA2414 09 52.8 -01 34 21.5              660     82.9
   CE8TQD2 11 14.8 -01 21 20.7              660     82.7
   P12lDlR 08 46.7 -00 45 22.4              645     82.0
   C45W821 11 42.7 -00 27 19.7              660     81.8
   CE7Y2P2 10 18.4 -00 23 21.0              645     81.6
    X89255 11 21.3 -00 12 17.9              660     81.6
   ST26B48 09 56.4 -00 15 20.1              660     81.6
   C45W3X1 20 59.2 -18 03 30.1              660     80.7
   CE88H12 11 35.7 +01 35 21.3              645     79.8
   orA2763 12 34.9 +02 38 20.0              645     78.7
   CE8LNQ2 09 40.7 +02 40 20.8              660     78.7
   CE83CU2 10 53.7 +02 52 21.1              660     78.5
   CE8XFV2 12 23.3 +03 12 21.0              660     78.2
   CE8N232 09 59.9 +04 15 20.7              645     77.1
   CE7Y8A2 10 34.4 +05 20 20.6              645     76.0
   ODI2462 14 04.3 +05 31 21.5              645     75.8
   CE90Y32 14 57.3 +05 39 20.9              660     75.7
   A11yzTN 12 46.3 +05 58 19.5              645     75.3
   C1C7T05 12 14.6 +06 24 22.0              645     74.9
   C45W551 09 24.7 -23 45 20.6              690     74.9
   C1C60U5 09 45.3 +07 28 22.6              645     73.9
   T61JM01 09 40.7 +07 33 18.5              660     73.8
   CE7PRF2 09 42.1 +07 35 21.6              645     73.8
   T61JM02 09 42.7 +07 44 19.6              645     73.7
   CE8GYY2 12 24.5 +08 19 21.9              645     73.1
   CE8GHW2 12 17.6 +08 26 22.0              645     72.9
   CE82VN2 10 56.6 +08 36 21.7              645     72.8
   ST26B47 22 25.4 +08 46 32.4              615     72.4
   C1C4K95 08 29.4 +09 09 22.6              645     72.2
   P22lMSN 15 05.6 +09 25 21.9              645     71.9
   ST26B25 22 28.5 +09 40 34.6              630     71.5
   P22l8RJ 13 08.3 -27 10 21.6              690     71.4
   C1C3XP5 08 22.9 +09 59 21.9              645     71.3
   CE7LUH2 08 38.7 +10 38 20.7              630     70.7
   CE7U292 09 44.4 +11 01 20.7              645     70.4
   P12lZEB 11 46.2 +11 16 19.8              645     70.1
   PDO0100 10 39.9 +12 12 21.1              630     69.2
   C1C7V05 12 47.4 +12 39 21.4              645     68.7
   CE7T552 09 35.8 +12 51 21.3              645     68.5
   C1CDFZ5 14 05.7 +14 29 21.5              645     66.9
   CE8AMJ2 11 30.8 +14 40 21.9              645     66.7
   P22lyTB 11 48.4 +15 04 21.6              645     66.3
   ZTF10Bf 13 47.3 +17 16 20.8              630     64.1
   P22lUn8 10 32.9 +17 46 21.4              615     63.6
   C45WET1 09 13.6 +18 48 19.2              630     62.6
   CE7F722 10 38.6 +18 55 21.6              630     62.5
   P22lUn6 10 42.8 +19 10 21.9              630     62.2
   Sar2869 10 00.8 +19 37 20.5              615     61.8
   ZTF10Bg 20 27.4 -37 00 24.0              675     61.8
   C45W2H1 09 19.1 +20 47 20.1              615     60.5
   C1CA1K5 08 59.8 +20 57 21.1              615     60.4
   C1CCA05 09 48.6 +21 15 20.7              615     60.1
   Sar2870 10 09.3 +22 07 19.0              630     59.3
   C1C9Y25 08 13.4 +23 15 22.1              615     58.1
   CE84E12 11 08.3 +25 34 21.1              615     55.8
   CE89FX2 13 13.3 -43 12 19.9              690     55.4
   ZTF10BB 20 26.9 +26 07 27.4              585     55.1
   C1CDCT5 12 31.9 +26 38 22.5              615     54.7
   C1CA1L5 08 15.1 +27 20 22.0              615     54.0
   C1CD7L5 11 48.9 +27 35 22.1              615     53.8
   A11yqBr 15 53.8 +29 01 19.4              600     52.3
   C1C7DN5 10 51.5 +29 16 22.5              600     52.1
   C1CD0E5 10 57.5 +29 39 22.7              600     51.8
   C1C7FZ5 10 45.9 +30 06 22.5              600     51.3
   C1CD955 11 55.2 +30 50 21.7              600     50.6
    X89042 11 15.5 +31 49 20.8              600     49.6
   C1C88V5 12 16.2 +32 01 21.7              600     49.4
   C1C7EZ5 10 38.0 +33 09 22.0              600     48.2
   C1CD665 11 19.3 +33 29 22.3              585     47.9
   ZTF10Bi 09 47.7 +34 31 18.1              585     46.9
   A11ynxx 18 21.0 +36 32 19.9              570     44.7
   C45W5U1 14 01.2 +38 30 19.3              585     42.9
   C45WJW1 15 35.9 +38 35 19.6              585     42.8
   C45WJF1 13 20.4 +40 24 19.6              570     41.0
   ZTF10BV 15 17.8 -61 55 22.8              705     36.7
   C1AZHH5 09 01.7 +51 09 24.0              525     30.2
   ST26B20 03 26.6 -69 36 26.6              675     29.2
   A11yweL 11 54.1 +57 46 22.0              450     23.7

------------------------------------------------------------